### ISSUE TITLE
标题和图片不对应

### ISSUE THREAD

**Issue by Hikyu** [dream2023/vue-ele-gallery#6]
比如：

有6张图片，分别为 img1 - img6，对应标题 title1 - title6

第一次加载，点击后查看大图，是正确的。比如，现在查看 img4

关闭大图对话框，重新选择 img1 ，点击查看大图，发现标题是 title1，但是图片实际上是 img4

**Comment by Hikyu** [comment]
应该用 setActiveItem 方法设置轮播图当前显示的图片

**Comment by dream2023** [comment]
已解决
